- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: no
  tasks:
    - name: Install Erlang Repository Package
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
        state: present
      tags:
        - package

    - name: Add Erlang Solutions public key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      tags:
        - package

    - name: Add Erlang Solutions repository
      apt_repository:
        repo: 'deb https://packages.erlang-solutions.com/ubuntu bionic contrib'
        state: present
        filename: 'erlang-solutions'
      tags:
        - package

    - name: Install Erlang
      apt:
        name: erlang
        update_cache: yes
        cache_valid_time: 86400
        state: present
      tags:
        - package

    - name: Add RabbitMQ signing key
      apt_key:
        url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present
      tags:
        - package

    - name: Add RabbitMQ repository
      apt_repository:
        repo: 'deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main'
        state: present
        filename: 'rabbitmq-server'
      tags:
        - package

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
      tags:
        - package

    - name: Start & Enable RabbitMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Configure RabbitMQ
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RabbitMQ
      tags:
        - conf

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RabbitMQ
      tags:
        - conf

    - name: Enable the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RabbitMQ
      tags:
        - package

  handlers:
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
